return {
    check = {
        ["check.png"] = "rbxassetid://17371694141",
        ["error.png"] = "rbxassetid://17371694391",
        ["focus.png"] = "rbxassetid://17371694738",
        ["skip.png"] = "rbxassetid://17371695106",
        ["todo.png"] = "rbxassetid://17371695382",
    },
    status = {
        ["connected.png"] = "rbxassetid://17371695681",
        ["disconnected.png"] = "rbxassetid://17371695870",
    },
}